#!/bin/pwsh

[CmdletBinding()]
param(
    [Parameter(Position = 0, Mandatory = $True)]
    $IcoFilename
)

$scriptPath = [System.Environment]::GetEnvironmentVariable('_')
$script = Get-Item -Path $scriptPath | Select LinkType, Target
if ($script.LinkType -eq "SymbolicLink") {
    $scriptPath = $script.Target
}

$iconScriptsDir = [System.IO.Path]::GetDirectoryName($scriptPath)
$scriptsDir = [System.IO.Path]::GetDirectoryName($iconScriptsDir)

$pythonPath = $iconScriptsDir + ":" + $scriptsDir
[System.Environment]::SetEnvironmentVariable('PYTHONPATH', $pythonPath)

$iconName = [System.IO.Path]::GetFileName($IcoFilename).Replace(' ', '-').Replace('.ico', '-ico')
Write-Host "Executing python $iconScriptsDir/xdg_icon_resource_install_ico.py $IcoFilename --name $iconName --context apps --sudo"
python $iconScriptsDir/xdg_icon_resource_install_ico.py $IcoFilename --name $iconName --context apps --sudo
