// See https://aka.ms/new-console-template for more information


using DecompiledAssemblySourcesTool;
using System.CommandLine;

var options = new[] { new Option<string>(new[] { "--csproj", "-c" }, "Full filepath to the .csproj generated by dotPeek containing ItemGroup references to decompiled sources.") { IsRequired = true } }.ToDictionary(option => option.Name);

var rootCommand = new RootCommand("Process a directory of decompiled sources from dotPeek, renaming files to match class names and moving into directories matching the assembly names.") { options["csproj"] };
rootCommand.SetHandler((string csproj) =>
{
    var csprojObj = new Csproj(csproj);
    foreach (var file in csprojObj.CompileIncludes.Where(file => file.EndsWith(".cs")))
    {
        var csClass = new CSharpFile(file);
        if (csClass.TopLevelIdentifiers.Where(i => ie)
        {
            Console.Out.WriteLine(csClass);
        }
    }
}, options["csproj"]);

rootCommand.Invoke(args);

